-- Sample data for MusicApp
-- Seed the database with initial artists, albums, and songs

-- Insert sample user
INSERT INTO users (username, email, display_name) VALUES 
('demo_user', 'demo@musicapp.com', 'Demo User');

-- Insert artists
INSERT INTO artists (name, bio) VALUES 
('Luna Rivers', 'Electronic music producer known for atmospheric sounds'),
('Atlas Grey', 'Indie rock artist with a coastal vibe'),
('Mara Vale', 'Singer-songwriter creating mellow acoustic tracks'),
('Echo Arcade', 'Synthwave and retrowave producer'),
('Novah', 'Experimental electronic artist'),
('Indigo Frame', 'High-energy EDM and dance music'),
('Cora Mae', 'Folk and indie pop artist'),
('Velvet Pilot', 'Alternative rock with upbeat energy'),
('Northbound', 'Ambient and focus music producer'),
('Sienna Coast', 'Chill and lo-fi hip hop artist'),
('Crimson Wave', 'Energetic rock band with powerful vocals'),
('Starlight Echo', 'Dreamy synth-pop duo'),
('Midnight Theory', 'Dark ambient and downtempo artist'),
('Phoenix Harmony', 'Uplifting orchestral and cinematic music'),
('Neon Pulse', 'Retro 80s synthwave producer'),
('Azure Dreams', 'Chill electronic and chillwave artist'),
('Thunder Road', 'Classic rock inspired modern band'),
('Crystal Mind', 'Meditative and focus ambient music'),
('Urban Souls', 'Contemporary R&B and soul artist'),
('Wild Bloom', 'Indie folk with organic instrumentation');

-- Insert albums
INSERT INTO albums (title, artist_id, release_date) VALUES 
('City Glow', 1, '2023-03-15'),
('Blue Horizon', 2, '2023-05-20'),
('Sunset Stories', 3, '2023-07-10'),
('Late Drive', 4, '2023-09-05'),
('Signal', 5, '2023-11-12'),
('Terminal', 6, '2024-01-08'),
('Fine Lines', 7, '2024-03-22'),
('Gravity', 8, '2024-05-30'),
('Static', 9, '2024-07-18'),
('Open Sky', 10, '2024-09-25'),
('Electric Storm', 11, '2024-02-14'),
('Cosmic Dreams', 12, '2024-04-18'),
('Dark Waters', 13, '2024-06-22'),
('Rising Sun', 14, '2024-08-30'),
('Neon Nights', 15, '2024-10-15'),
('Azure Waves', 16, '2024-11-20'),
('Thunder Strike', 17, '2023-12-05'),
('Inner Peace', 18, '2024-01-25'),
('Velvet Voice', 19, '2024-03-10'),
('Forest Path', 20, '2024-05-12');

-- Insert songs with YouTube links
-- Note: These are placeholder YouTube IDs. Replace with actual music video IDs
INSERT INTO songs (title, artist_id, album_id, youtube_url, youtube_id, duration, mood) VALUES 
('Neon Streets', 1, 1, 'https://youtube.com/watch?v=dQw4w9WgXcQ', 'dQw4w9WgXcQ', 212, 'Energy'),
('Coastline', 2, 2, 'https://youtube.com/watch?v=jNQXAC9IVRw', 'jNQXAC9IVRw', 248, 'Chill'),
('Golden Hour', 3, 3, 'https://youtube.com/watch?v=9bZkp7q19f0', '9bZkp7q19f0', 177, 'Chill'),
('Night Shift', 4, 4, 'https://youtube.com/watch?v=y6120QOlsfU', 'y6120QOlsfU', 224, 'Focus'),
('Static Bloom', 5, 5, 'https://youtube.com/watch?v=kJQP7kiw5Fk', 'kJQP7kiw5Fk', 195, 'Focus'),
('Runway Lights', 6, 6, 'https://youtube.com/watch?v=lXMskKTw3Bc', 'lXMskKTw3Bc', 238, 'Energy'),
('Paper Planes', 7, 7, 'https://youtube.com/watch?v=rYEDA3JcQqw', 'rYEDA3JcQqw', 201, 'Classic'),
('Falling Up', 8, 8, 'https://youtube.com/watch?v=fJ9rUzIMcZQ', 'fJ9rUzIMcZQ', 242, 'Energy'),
('Quiet Signal', 9, 9, 'https://youtube.com/watch?v=QH2-TGUlwu4', 'QH2-TGUlwu4', 185, 'Focus'),
('Horizon Line', 10, 10, 'https://youtube.com/watch?v=nfWlot6h_JM', 'nfWlot6h_JM', 227, 'Chill'),
('Thunder Strike', 11, 11, 'https://youtube.com/watch?v=3tmd-ClpJxA', '3tmd-ClpJxA', 215, 'Energy'),
('Breaking Free', 11, 11, 'https://youtube.com/watch?v=2Vv-BfVoq4g', '2Vv-BfVoq4g', 198, 'Energy'),
('Stargazer', 12, 12, 'https://youtube.com/watch?v=5qap5aO4i9A', '5qap5aO4i9A', 234, 'Chill'),
('Velvet Sky', 12, 12, 'https://youtube.com/watch?v=oHg5SJYRHA0', 'oHg5SJYRHA0', 267, 'Chill'),
('Deep Dive', 13, 13, 'https://youtube.com/watch?v=ZZ5LpwO-An4', 'ZZ5LpwO-An4', 312, 'Focus'),
('Shadows Dance', 13, 13, 'https://youtube.com/watch?v=hLQl3WQQoQ0', 'hLQl3WQQoQ0', 289, 'Focus'),
('Victory March', 14, 14, 'https://youtube.com/watch?v=RgKAFK5djSk', 'RgKAFK5djSk', 256, 'Classic'),
('New Dawn', 14, 14, 'https://youtube.com/watch?v=IxuThNgl3YA', 'IxuThNgl3YA', 301, 'Classic'),
('Retro Drive', 15, 15, 'https://youtube.com/watch?v=MV_3Dpw-BRY', 'MV_3Dpw-BRY', 223, 'Energy'),
('Synthwave Sunset', 15, 15, 'https://youtube.com/watch?v=cU8HrO7XuiE', 'cU8HrO7XuiE', 245, 'Chill'),
('Ocean Breeze', 16, 16, 'https://youtube.com/watch?v=vTIIMJ9tUc8', 'vTIIMJ9tUc8', 198, 'Chill'),
('Morning Light', 16, 16, 'https://youtube.com/watch?v=Zi_XLOBDo_Y', 'Zi_XLOBDo_Y', 221, 'Chill'),
('Highway Rider', 17, 17, 'https://youtube.com/watch?v=xO1TScQwu6g', 'xO1TScQwu6g', 267, 'Classic'),
('Rock Anthem', 17, 17, 'https://youtube.com/watch?v=RY_2gElt3SA', 'RY_2gElt3SA', 243, 'Energy'),
('Meditation Flow', 18, 18, 'https://youtube.com/watch?v=lTRiuFIWV54', 'lTRiuFIWV54', 432, 'Focus'),
('Zen Garden', 18, 18, 'https://youtube.com/watch?v=WPni755-Krg', 'WPni755-Krg', 387, 'Focus'),
('Smooth Operator', 19, 19, 'https://youtube.com/watch?v=4TYv2PhG89A', '4TYv2PhG89A', 189, 'Chill'),
('Soul Fire', 19, 19, 'https://youtube.com/watch?v=fbGUEelmzxo', 'fbGUEelmzxo', 211, 'Classic'),
('Mountain Trail', 20, 20, 'https://youtube.com/watch?v=S-Xm7s9eGxU', 'S-Xm7s9eGxU', 276, 'Chill'),
('Wildflower', 20, 20, 'https://youtube.com/watch?v=IcrbM1l_BoI', 'IcrbM1l_BoI', 234, 'Classic'),
-- Additional songs (31-100)
('City Lights', 1, 1, 'https://youtube.com/watch?v=E8gmARGvPlI', 'E8gmARGvPlI', 195, 'Energy'),
('Midnight Echo', 1, 1, 'https://youtube.com/watch?v=hT_nvWreIhg', 'hT_nvWreIhg', 218, 'Chill'),
('Digital Dreams', 1, 1, 'https://youtube.com/watch?v=2vjPBrBU-TM', '2vjPBrBU-TM', 232, 'Focus'),
('Sunset Boulevard', 2, 2, 'https://youtube.com/watch?v=GlCFPo6YYbU', 'GlCFPo6YYbU', 265, 'Chill'),
('Ocean Drive', 2, 2, 'https://youtube.com/watch?v=iNzrwh2Z2hQ', 'iNzrwh2Z2hQ', 241, 'Energy'),
('Coastal Breeze', 2, 2, 'https://youtube.com/watch?v=b6vSf0cA9qY', 'b6vSf0cA9qY', 198, 'Chill'),
('Autumn Leaves', 3, 3, 'https://youtube.com/watch?v=r8OipmKFDeM', 'r8OipmKFDeM', 213, 'Classic'),
('Spring Morning', 3, 3, 'https://youtube.com/watch?v=6btFObRRD9k', '6btFObRRD9k', 187, 'Chill'),
('Winter Tales', 3, 3, 'https://youtube.com/watch?v=jfKfPfyJRdk', 'jfKfPfyJRdk', 256, 'Focus'),
('Summer Nights', 3, 3, 'https://youtube.com/watch?v=bpOSxM0rNPM', 'bpOSxM0rNPM', 229, 'Energy'),
('Neon Arcade', 4, 4, 'https://youtube.com/watch?v=HMnrl0tmd3k', 'HMnrl0tmd3k', 207, 'Energy'),
('Retro Wave', 4, 4, 'https://youtube.com/watch?v=MH9FyLsfDzw', 'MH9FyLsfDzw', 234, 'Chill'),
('80s Vibes', 4, 4, 'https://youtube.com/watch?v=rDBbaGCCIhk', 'rDBbaGCCIhk', 278, 'Classic'),
('Cyber City', 4, 4, 'https://youtube.com/watch?v=MVPTGNGiI-4', 'MVPTGNGiI-4', 245, 'Focus'),
('Glitch Art', 5, 5, 'https://youtube.com/watch?v=aGSKrC7dGcY', 'aGSKrC7dGcY', 198, 'Focus'),
('Binary Code', 5, 5, 'https://youtube.com/watch?v=bIJcHvDnvJc', 'bIJcHvDnvJc', 312, 'Focus'),
('Data Flow', 5, 5, 'https://youtube.com/watch?v=sCNrK-n68CM', 'sCNrK-n68CM', 287, 'Energy'),
('Circuit Break', 5, 5, 'https://youtube.com/watch?v=qeMFqkcPYcg', 'qeMFqkcPYcg', 223, 'Focus'),
('Dance Floor', 6, 6, 'https://youtube.com/watch?v=k4Xx0k_TVY0', 'k4Xx0k_TVY0', 189, 'Energy'),
('Club Night', 6, 6, 'https://youtube.com/watch?v=gCYcHz2k5x0', 'gCYcHz2k5x0', 256, 'Energy'),
('Party Anthem', 6, 6, 'https://youtube.com/watch?v=ym1quwoh9cQ', 'ym1quwoh9cQ', 234, 'Energy'),
('Bass Drop', 6, 6, 'https://youtube.com/watch?v=mj-v6zCnEaw', 'mj-v6zCnEaw', 267, 'Energy'),
('Morning Dew', 7, 7, 'https://youtube.com/watch?v=iX-QaNzd-0Y', 'iX-QaNzd-0Y', 178, 'Chill'),
('Sunset Dreams', 7, 7, 'https://youtube.com/watch?v=tGvHNNOLnCk', 'tGvHNNOLnCk', 245, 'Chill'),
('Moonlight', 7, 7, 'https://youtube.com/watch?v=0yW7w8F2TVA', '0yW7w8F2TVA', 298, 'Classic'),
('Starlight', 7, 7, 'https://youtube.com/watch?v=u1ZB_rGFyeU', 'u1ZB_rGFyeU', 213, 'Chill'),
('Rocket Ship', 8, 8, 'https://youtube.com/watch?v=rTga41r3a4s', 'rTga41r3a4s', 221, 'Energy'),
('Sky High', 8, 8, 'https://youtube.com/watch?v=w3xcybdis1k', 'w3xcybdis1k', 198, 'Energy'),
('Cloud Nine', 8, 8, 'https://youtube.com/watch?v=hT6WW81FcoM', 'hT6WW81FcoM', 287, 'Chill'),
('Atmosphere', 8, 8, 'https://youtube.com/watch?v=vWaljXUiCaE', 'vWaljXUiCaE', 312, 'Focus'),
('Deep Focus', 9, 9, 'https://youtube.com/watch?v=5P6ADakiwcg', '5P6ADakiwcg', 456, 'Focus'),
('Study Session', 9, 9, 'https://youtube.com/watch?v=2OEL4P1Rz04', '2OEL4P1Rz04', 389, 'Focus'),
('Work Mode', 9, 9, 'https://youtube.com/watch?v=1hPxGmTGarM', '1hPxGmTGarM', 421, 'Focus'),
('Concentration', 9, 9, 'https://youtube.com/watch?v=jIxas0a-KgM', 'jIxas0a-KgM', 367, 'Focus'),
('Lazy Sunday', 10, 10, 'https://youtube.com/watch?v=rR2rZAYW-WQ', 'rR2rZAYW-WQ', 198, 'Chill'),
('Coffee Shop', 10, 10, 'https://youtube.com/watch?v=wEIwN37E8xM', 'wEIwN37E8xM', 234, 'Chill'),
('Rainy Day', 10, 10, 'https://youtube.com/watch?v=8plwv25NYRo', '8plwv25NYRo', 289, 'Chill'),
('Cozy Vibes', 10, 10, 'https://youtube.com/watch?v=r0zj3XCWQM4', 'r0zj3XCWQM4', 267, 'Chill'),
('Lightning Storm', 11, 11, 'https://youtube.com/watch?v=P5mG-xM6T4c', 'P5mG-xM6T4c', 243, 'Energy'),
('Wild Thunder', 11, 11, 'https://youtube.com/watch?v=wK7EqB-lFyk', 'wK7EqB-lFyk', 256, 'Energy'),
('Rock Solid', 11, 11, 'https://youtube.com/watch?v=e8awRFHPX24', 'e8awRFHPX24', 298, 'Classic'),
('Electric Soul', 11, 11, 'https://youtube.com/watch?v=BxuY9FET9Y4', 'BxuY9FET9Y4', 221, 'Energy'),
('Nebula', 12, 12, 'https://youtube.com/watch?v=FjNdYp2gXRY', 'FjNdYp2gXRY', 312, 'Chill'),
('Galaxy', 12, 12, 'https://youtube.com/watch?v=wOMwO5T3yT4', 'wOMwO5T3yT4', 287, 'Focus'),
('Constellation', 12, 12, 'https://youtube.com/watch?v=4GE7QYc9HfM', '4GE7QYc9HfM', 345, 'Chill'),
('Meteor Shower', 12, 12, 'https://youtube.com/watch?v=LsoLEjrDogU', 'LsoLEjrDogU', 298, 'Energy'),
('Dark Night', 13, 13, 'https://youtube.com/watch?v=tkzY_VwNIek', 'tkzY_VwNIek', 398, 'Focus'),
('Shadow World', 13, 13, 'https://youtube.com/watch?v=tnR1NZhyQSo', 'tnR1NZhyQSo', 412, 'Focus'),
('Mystic Forest', 13, 13, 'https://youtube.com/watch?v=qZIQAk-BUEc', 'qZIQAk-BUEc', 367, 'Chill'),
('Haunted Dreams', 13, 13, 'https://youtube.com/watch?v=FKSy-BrdF-I', 'FKSy-BrdF-I', 389, 'Focus'),
('Hope Rising', 14, 14, 'https://youtube.com/watch?v=JvXxvpWdh4k', 'JvXxvpWdh4k', 289, 'Classic'),
('Victory Song', 14, 14, 'https://youtube.com/watch?v=QfMhvjCRKhI', 'QfMhvjCRKhI', 312, 'Energy'),
('Triumph', 14, 14, 'https://youtube.com/watch?v=hKRUPYrAQoE', 'hKRUPYrAQoE', 267, 'Classic'),
('Glory Days', 14, 14, 'https://youtube.com/watch?v=bWcASV2sey0', 'bWcASV2sey0', 298, 'Energy'),
('Miami Vice', 15, 15, 'https://youtube.com/watch?v=qeaU8yyBOf4', 'qeaU8yyBOf4', 234, 'Energy'),
('Synthwave City', 15, 15, 'https://youtube.com/watch?v=I6Rc66gRjb0', 'I6Rc66gRjb0', 256, 'Chill'),
('Neon Paradise', 15, 15, 'https://youtube.com/watch?v=tLyRpGKWXRs', 'tLyRpGKWXRs', 287, 'Energy'),
('Retro Future', 15, 15, 'https://youtube.com/watch?v=kfoJUeyMsOE', 'kfoJUeyMsOE', 245, 'Focus'),
('Crystal Waters', 16, 16, 'https://youtube.com/watch?v=7lbFRYF-bbM', '7lbFRYF-bbM', 198, 'Chill'),
('Blue Lagoon', 16, 16, 'https://youtube.com/watch?v=mRD0-GxqHVo', 'mRD0-GxqHVo', 223, 'Chill'),
('Tropical Paradise', 16, 16, 'https://youtube.com/watch?v=9JDzlhW3XTM', '9JDzlhW3XTM', 267, 'Chill'),
('Island Vibes', 16, 16, 'https://youtube.com/watch?v=X_8Nh5XfRw0', 'X_8Nh5XfRw0', 234, 'Energy'),
('Born to Run', 17, 17, 'https://youtube.com/watch?v=f3t9SfrfDZM', 'f3t9SfrfDZM', 289, 'Classic'),
('Thunder Road Band', 17, 17, 'https://youtube.com/watch?v=72kbV-_AdaA', '72kbV-_AdaA', 312, 'Energy'),
('Classic Ride', 17, 17, 'https://youtube.com/watch?v=xih-Xfk1kDg', 'xih-Xfk1kDg', 298, 'Classic'),
('Rock Legend', 17, 17, 'https://youtube.com/watch?v=gOMhN-hfMtY', 'gOMhN-hfMtY', 267, 'Energy'),
('Peace Within', 18, 18, 'https://youtube.com/watch?v=FLdL6K7qm_Q', 'FLdL6K7qm_Q', 498, 'Focus'),
('Mindful Moments', 18, 18, 'https://youtube.com/watch?v=eKFTSSKCzWA', 'eKFTSSKCzWA', 456, 'Focus'),
('Tranquility', 18, 18, 'https://youtube.com/watch?v=bVjhCIvzOdU', 'bVjhCIvzOdU', 512, 'Focus'),
('Serenity Now', 18, 18, 'https://youtube.com/watch?v=wvNg7Hq10bU', 'wvNg7Hq10bU', 423, 'Focus'),
('Velvet Touch', 19, 19, 'https://youtube.com/watch?v=aWmkuH1k7uA', 'aWmkuH1k7uA', 198, 'Chill'),
('Soulful Night', 19, 19, 'https://youtube.com/watch?v=6okxuiiHx2w', '6okxuiiHx2w', 223, 'Classic'),
('Groove Street', 19, 19, 'https://youtube.com/watch?v=HEXWRTEbj1I', 'HEXWRTEbj1I', 245, 'Energy'),
('R&B Classic', 19, 19, 'https://youtube.com/watch?v=vMf3JlFDdnY', 'vMf3JlFDdnY', 267, 'Classic'),
('Nature Walk', 20, 20, 'https://youtube.com/watch?v=3nQNiWdeH2Q', '3nQNiWdeH2Q', 289, 'Chill'),
('Forest Song', 20, 20, 'https://youtube.com/watch?v=h7tFUrVaEGk', 'h7tFUrVaEGk', 234, 'Focus'),
('Green Meadows', 20, 20, 'https://youtube.com/watch?v=W3Gvuq0a6rw', 'W3Gvuq0a6rw', 312, 'Chill'),
('Mountain Breeze', 20, 20, 'https://youtube.com/watch?v=jIHT5WVJ7fA', 'jIHT5WVJ7fA', 267, 'Classic');

-- Create a sample playlist
INSERT INTO playlists (user_id, name, description, is_public) VALUES 
(1, 'Daily Mix', 'Your personalized mix of favorites', 1),
(1, 'Focus Sessions', 'Concentration music for work and study', 1),
(1, 'Energy Boost', 'High-energy tracks to pump you up', 1);

-- Add songs to playlists
INSERT INTO playlist_songs (playlist_id, song_id, position) VALUES 
(1, 1, 1), (1, 2, 2), (1, 3, 3), (1, 7, 4),
(2, 4, 1), (2, 5, 2), (2, 9, 3),
(3, 1, 1), (3, 6, 2), (3, 8, 3);

-- Add some likes
INSERT INTO user_likes (user_id, song_id) VALUES 
(1, 1), (1, 3), (1, 9);

-- Add play history
INSERT INTO play_history (user_id, song_id) VALUES 
(1, 1), (1, 2), (1, 3), (1, 1);
